filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            equals:
              docker.container.labels.co_elastic_logs: "enabled"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              exclude_lines: ["^\\s+[\\-`'|.]+"]
              multiline:
                type: pattern
                pattern: '^\s'
                negate: false
                match: after

filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    exclude_lines: ["^\\s+[\\-`'|.]+"]
    multiline:
      type: pattern
      pattern: '^\s'
      negate: false
      match: after

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_host_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true
      process_array: false
      max_depth: 5

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: false
logging.to_syslog: false
