apiVersion: v1
kind: Service
metadata:
  name: rwa-backend-svc
  namespace: rwa-marketplace
  labels:
    app: rwa-backend
    component: backend
spec:
  selector:
    app: rwa-backend
  type: ClusterIP
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
