// Copyright (c) 2026 Tokenized Fractional RWA Marketplace Contributors
// SPDX-License-Identifier: MIT

/**
 * src/utils/httpProblem.js — RFC 7807 "Problem Details for HTTP APIs".
 *
 * Provides a shared vocabulary for returning machine-readable error details
 * from every endpoint. Every `ProblemError` (or normalized legacy error
 * payload) renders as an `application/problem+json` document with the
 * mandatory RFC 7807 members:
 *
 *   - type:     URI reference identifying the problem type
 *   - title:    short human-readable summary of the problem type
 *   - status:   HTTP status code generated by the origin server
 *   - detail:   human-readable explanation specific to this occurrence
 *   - instance: URI reference identifying the specific occurrence
 *
 * Extension members (e.g. `code`, `requestId`, `reason`) are permitted by the
 * spec and may be attached via `extensions`.
 */

export const PROBLEM_CONTENT_TYPE = 'application/problem+json';

// Terse, spec-aligned titles for the most common status codes.
export const STATUS_TITLES = {
  400: 'Bad Request',
  401: 'Unauthorized',
  402: 'Payment Required',
  403: 'Forbidden',
  404: 'Not Found',
  405: 'Method Not Allowed',
  406: 'Not Acceptable',
  409: 'Conflict',
  410: 'Gone',
  413: 'Payload Too Large',
  415: 'Unsupported Media Type',
  422: 'Unprocessable Entity',
  429: 'Too Many Requests',
  500: 'Internal Server Error',
  501: 'Not Implemented',
  502: 'Bad Gateway',
  503: 'Service Unavailable',
  504: 'Gateway Timeout',
};

/**
 * Status code → stable problem-type slug used to build a `type` URI.
 * Falls back to `about:blank` when no slug is registered.
 */
function slugForStatus(status, customSlug) {
  if (customSlug) return customSlug;
  const map = {
    400: 'bad-request',
    401: 'unauthorized',
    402: 'payment-required',
    403: 'forbidden',
    404: 'not-found',
    405: 'method-not-allowed',
    409: 'conflict',
    413: 'payload-too-large',
    415: 'unsupported-media-type',
    422: 'unprocessable-entity',
    429: 'too-many-requests',
    500: 'internal-server-error',
    502: 'bad-gateway',
    503: 'service-unavailable',
    504: 'gateway-timeout',
  };
  return map[status] || 'about:blank';
}

function defaultTitle(status) {
  return STATUS_TITLES[status] || status >= 500 ? 'Server Error' : 'Request Error';
}

/**
 * Normalize any caught error / legacy payload into an RFC 7807 problem object.
 *
 * @param {string|Error|object} source
 *   - string:            used as `detail`
 *   - Error/ProblemError: uses `message`/`detail`, optionally `status`, `type`,
 *                         `title`, `code`, `extensions`
 *   - object:            legacy response shapes like `{ error, code, reason,
 *                         message, requestId, status, title, type, detail,
 *                         instance, extensions }` are flattened.
 * @param {object} [req]  Express request; used to build the `instance` field.
 * @param {number} [resStatusCode] Status code already set on the response
 *                        (used when `source` does not carry an explicit status).
 * @returns {{type:string,title:string,status:number,detail:string,instance:string,[k:string]:unknown}}
 */
export function toProblemResponse(source, req, resStatusCode) {
  const fallbackStatus = Number(resStatusCode) >= 400 ? Number(resStatusCode) : 500;
  let status = fallbackStatus;
  let detail = '';
  let type;
  let title;
  let code;
  let reason;
  let requestId;
  let extensions = {};
  let customSlug;

  const path = req?.originalUrl || req?.url || '/';
  const instance = req?.requestId ? `${path}#${req.requestId}` : path;

  if (typeof source === 'string') {
    detail = source;
  } else if (source instanceof Error) {
    detail = source.message || '';
    status = Number(source.status) || Number(source.statusCode) || 500;
    type = source.type;
    title = source.title;
    code = source.code;
    customSlug = source.typeSlug;
    if (source.extensions && typeof source.extensions === 'object') {
      extensions = { ...source.extensions };
    }
  } else if (source && typeof source === 'object') {
    // RFC 7807 passthrough
    if (typeof source.type === 'string') type = source.type;
    if (typeof source.title === 'string') title = source.title;
    if (typeof source.detail === 'string') detail = source.detail;
    if (typeof source.instance === 'string') {
      // instance overrides derived occurrence reference
    }
    status = Number(source.status) || Number(source.statusCode) || fallbackStatus;
    // Legacy shapes
    if (source.error !== undefined) detail = String(source.error);
    if (source.message !== undefined && !detail) detail = String(source.message);
    if (source.code !== undefined) code = source.code;
    if (source.reason !== undefined) reason = source.reason;
    if (source.requestId !== undefined) requestId = source.requestId;
    if (source.title) title = source.title;
    if (source.extensions && typeof source.extensions === 'object') {
      extensions = { ...source.extensions };
    }
  }

  const finalType =
    type || (customSlug ? `about:blank#${customSlug}` : `about:blank#${slugForStatus(status)}`);
  const finalTitle =
    title || defaultTitle(status);
  const finalDetail =
    detail || finalTitle || 'The server encountered an unexpected condition.';

  const body = {
    type: finalType,
    title: finalTitle,
    status,
    detail: finalDetail,
    instance,
  };

  if (code !== undefined) body.code = code;
  if (reason !== undefined) body.reason = reason;
  if (requestId !== undefined) body.requestId = requestId;
  // Extension members from ProblemError or thrown errors.
  for (const [key, value] of Object.entries(extensions)) {
    if (value === undefined || key === 'code') continue;
    if (body[key] !== undefined) continue;
    body[key] = value;
  }

  return body;
}

/**
 * Thrown → global error handler response document.
 * Mirrors `toProblemResponse` but guarantees a stable 5xx shape for
 * genuinely unexpected errors and prevents leaking stack details.
 */
export function toProblemErrorResponse(err, req, production = false) {
  const status = Number(err.status) || Number(err.statusCode) || 500;
  const path = req?.originalUrl || req?.url || '/';
  const instance = req?.requestId ? `${path}#${req.requestId}` : path;
  const code = err.code;

  const title =
    err.title ||
    STATUS_TITLES[status] ||
    (status >= 500 ? 'Internal Server Error' : 'Request Error');

  let detail = err.detail || (err instanceof Error ? err.message : undefined);
  if (!detail || (status >= 500 && production)) {
    detail = title;
  }

  const body = {
    type: err.type || `about:blank#${slugForStatus(status)}`,
    title,
    status,
    detail,
    instance,
  };
  if (code !== undefined) body.code = code;
  return body;
}

function characteristicSlug(detail) {
  const slug = String(detail)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
  return slug.slice(0, 40) || 'conflict';
}

/**
 * Build a ProblemError for throwing inside handlers / services.
 *
 * @example
 *   throw problem(404, 'Asset metadata not found', { code: 'ASSET_NOT_FOUND' });
 */
export function problem(status, detail, options = {}) {
  const { code, title, type, typeSlug, instance, extensions } = options;
  const err = new ProblemError(detail, status);
  err.status = Number(status);
  if (code !== undefined) err.code = code;
  if (title !== undefined) err.title = title;
  if (type !== undefined) err.type = type;
  if (typeSlug !== undefined) err.typeSlug = typeSlug;
  if (instance !== undefined) err.instance = instance;
  if (extensions !== undefined) err.extensions = extensions;
  return err;
}

/**
 * Error subclass carrying RFC 7807 members.
 */
export class ProblemError extends Error {
  constructor(detail, status = 500) {
    super(detail);
    this.name = 'ProblemError';
    this.status = Number(status);
    this.expose = true;
  }

  toJSON() {
    return toProblemResponse(this);
  }
}
